# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actuator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'actuator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63tuator.proto\x12\x08\x61\x63tuator\"%\n\x0e\x43ommandRequest\x12\x13\n\x0b\x64\x65vice_type\x18\x01 \x01(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x89\x01\n\x08\x41\x63tuator\x12<\n\x05Ligar\x12\x18.actuator.CommandRequest\x1a\x19.actuator.CommandResponse\x12?\n\x08\x44\x65sligar\x12\x18.actuator.CommandRequest\x1a\x19.actuator.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actuator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=28
  _globals['_COMMANDREQUEST']._serialized_end=65
  _globals['_COMMANDRESPONSE']._serialized_start=67
  _globals['_COMMANDRESPONSE']._serialized_end=100
  _globals['_ACTUATOR']._serialized_start=103
  _globals['_ACTUATOR']._serialized_end=240
# @@protoc_insertion_point(module_scope)
