# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csystem.proto\x12\x06system\x1a\x0cnanopb.proto\"y\n\nSensorData\x12\x1a\n\x0b\x64\x65vice_type\x18\x01 \x01(\tB\x05\x92?\x02p \x12\x18\n\tsensor_id\x18\x02 \x01(\tB\x05\x92?\x02p\x10\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x13\n\x04unit\x18\x04 \x01(\tB\x05\x92?\x02p\x08\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"o\n\x0f\x41\x63tuatorCommand\x12\x1a\n\x0b\x64\x65vice_type\x18\x01 \x01(\tB\x05\x92?\x02p \x12\x1a\n\x0b\x61\x63tuator_id\x18\x02 \x01(\tB\x05\x92?\x02p\x10\x12\x15\n\x06\x61\x63tion\x18\x03 \x01(\tB\x05\x92?\x02p\x10\x12\r\n\x05value\x18\x04 \x01(\x05\"E\n\x10\x41\x63tuatorResponse\x12\x1a\n\x0b\x61\x63tuator_id\x18\x01 \x01(\tB\x05\x92?\x02p\x10\x12\x15\n\x06status\x18\x02 \x01(\tB\x05\x92?\x02p\x10\x32O\n\x08\x41\x63tuator\x12\x43\n\x0e\x45xecuteCommand\x12\x17.system.ActuatorCommand\x1a\x18.system.ActuatorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA'].fields_by_name['device_type']._loaded_options = None
  _globals['_SENSORDATA'].fields_by_name['device_type']._serialized_options = b'\222?\002p '
  _globals['_SENSORDATA'].fields_by_name['sensor_id']._loaded_options = None
  _globals['_SENSORDATA'].fields_by_name['sensor_id']._serialized_options = b'\222?\002p\020'
  _globals['_SENSORDATA'].fields_by_name['unit']._loaded_options = None
  _globals['_SENSORDATA'].fields_by_name['unit']._serialized_options = b'\222?\002p\010'
  _globals['_ACTUATORCOMMAND'].fields_by_name['device_type']._loaded_options = None
  _globals['_ACTUATORCOMMAND'].fields_by_name['device_type']._serialized_options = b'\222?\002p '
  _globals['_ACTUATORCOMMAND'].fields_by_name['actuator_id']._loaded_options = None
  _globals['_ACTUATORCOMMAND'].fields_by_name['actuator_id']._serialized_options = b'\222?\002p\020'
  _globals['_ACTUATORCOMMAND'].fields_by_name['action']._loaded_options = None
  _globals['_ACTUATORCOMMAND'].fields_by_name['action']._serialized_options = b'\222?\002p\020'
  _globals['_ACTUATORRESPONSE'].fields_by_name['actuator_id']._loaded_options = None
  _globals['_ACTUATORRESPONSE'].fields_by_name['actuator_id']._serialized_options = b'\222?\002p\020'
  _globals['_ACTUATORRESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_ACTUATORRESPONSE'].fields_by_name['status']._serialized_options = b'\222?\002p\020'
  _globals['_SENSORDATA']._serialized_start=38
  _globals['_SENSORDATA']._serialized_end=159
  _globals['_ACTUATORCOMMAND']._serialized_start=161
  _globals['_ACTUATORCOMMAND']._serialized_end=272
  _globals['_ACTUATORRESPONSE']._serialized_start=274
  _globals['_ACTUATORRESPONSE']._serialized_end=343
  _globals['_ACTUATOR']._serialized_start=345
  _globals['_ACTUATOR']._serialized_end=424
# @@protoc_insertion_point(module_scope)
