/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SYSTEM_SYSTEM_PB_H_INCLUDED
#define PB_SYSTEM_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* ======================== [ MENSAGEM PARA SENSORES ] ======================== */
typedef struct _system_SensorData {
    char device_type[33]; /* Exemplo: "sensor_temperatura" */
    char sensor_id[17]; /* Identificador único do sensor */
    float value; /* Valor do sensor (exemplo: temperatura, umidade, luminosidade) */
    char unit[9]; /* Unidade de medida (°C, %, lux) */
    int64_t timestamp; /* Timestamp da leitura (opcional) */
} system_SensorData;

/* ======================== [ MENSAGEM PARA ATUADORES ] ======================== */
typedef struct _system_ActuatorCommand {
    char device_type[33]; /* Exemplo: "lampada", "motor" */
    char actuator_id[17]; /* Identificador único do atuador */
    char action[17]; /* Exemplo: "ligar", "desligar" */
    int32_t value; /* Parâmetro opcional (exemplo: intensidade da luz, velocidade) */
} system_ActuatorCommand;

/* ======================== [ RESPOSTA DO ATUADOR PARA O GATEWAY ] ======================== */
typedef struct _system_ActuatorResponse {
    char actuator_id[17]; /* Identificador único do atuador */
    char status[17]; /* Exemplo: "ligado", "desligado" */
} system_ActuatorResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define system_SensorData_init_default           {"", "", 0, "", 0}
#define system_ActuatorCommand_init_default      {"", "", "", 0}
#define system_ActuatorResponse_init_default     {"", ""}
#define system_SensorData_init_zero              {"", "", 0, "", 0}
#define system_ActuatorCommand_init_zero         {"", "", "", 0}
#define system_ActuatorResponse_init_zero        {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define system_SensorData_device_type_tag        1
#define system_SensorData_sensor_id_tag          2
#define system_SensorData_value_tag              3
#define system_SensorData_unit_tag               4
#define system_SensorData_timestamp_tag          5
#define system_ActuatorCommand_device_type_tag   1
#define system_ActuatorCommand_actuator_id_tag   2
#define system_ActuatorCommand_action_tag        3
#define system_ActuatorCommand_value_tag         4
#define system_ActuatorResponse_actuator_id_tag  1
#define system_ActuatorResponse_status_tag       2

/* Struct field encoding specification for nanopb */
#define system_SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_type,       1) \
X(a, STATIC,   SINGULAR, STRING,   sensor_id,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             3) \
X(a, STATIC,   SINGULAR, STRING,   unit,              4) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         5)
#define system_SensorData_CALLBACK NULL
#define system_SensorData_DEFAULT NULL

#define system_ActuatorCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_type,       1) \
X(a, STATIC,   SINGULAR, STRING,   actuator_id,       2) \
X(a, STATIC,   SINGULAR, STRING,   action,            3) \
X(a, STATIC,   SINGULAR, INT32,    value,             4)
#define system_ActuatorCommand_CALLBACK NULL
#define system_ActuatorCommand_DEFAULT NULL

#define system_ActuatorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   actuator_id,       1) \
X(a, STATIC,   SINGULAR, STRING,   status,            2)
#define system_ActuatorResponse_CALLBACK NULL
#define system_ActuatorResponse_DEFAULT NULL

extern const pb_msgdesc_t system_SensorData_msg;
extern const pb_msgdesc_t system_ActuatorCommand_msg;
extern const pb_msgdesc_t system_ActuatorResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define system_SensorData_fields &system_SensorData_msg
#define system_ActuatorCommand_fields &system_ActuatorCommand_msg
#define system_ActuatorResponse_fields &system_ActuatorResponse_msg

/* Maximum encoded size of messages (where known) */
#define SYSTEM_SYSTEM_PB_H_MAX_SIZE              system_ActuatorCommand_size
#define system_ActuatorCommand_size              81
#define system_ActuatorResponse_size             36
#define system_SensorData_size                   78

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
