/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(system_SensorData, system_SensorData, AUTO)


PB_BIND(system_ActuatorCommand, system_ActuatorCommand, AUTO)


PB_BIND(system_ActuatorResponse, system_ActuatorResponse, AUTO)



